### ISSUE TITLE
MINIR2 with no external antenna - won't connect to dhcp in DIY mode

### ISSUE THREAD

**Issue by CGabo** [itead/Sonoff_Devices_DIY_Tools#109]
New MiniR2 with 3.6 Firmware. Connected to the ITEAD App all ok, removed then and went to the DIY mode.

- Connect to Iteadxxxxx with password: 12345678 is working
- Select and config in browser http://10.10.7.1 is also working.
- Set up the device with following network settings:
    Network name:    sonoffDiy
    password:    20170618sn

    Network name:    SONOFF_DIY
    password:    20202020

Tried both as I was unsure which DIY mode is on the device. I assume it is V2.1 with the new name (SONOFF_DIY).
But with both settings, the device didn't get an IP from the DHCP Server. /  Test network with own router

Issue: in DIY mode the sonoff miniR2 don't connect to the DHCP Server

Question: What is the network name and password for the DIY mode and is there an issue with the MiniR2 / FW3.6 -> dhcp connect in DIY mode? Previous sonoff basic and mini with FW 3.3 were ok!
Thanks
Gab

**Comment by bkbartje** [comment]
You should set the network setting of your own network. That’s the only way it can connect to your network. Then from the dhcp server or with a tool you can find the op address within your network.
This manual worked for me
https://tasmota.github.io/docs/Sonoff-DIY/
Sonoff mini r2
I used postman instead of curl. But it worked perfectly. 
Step 2 was the hardest. But I see you are already past that.

**Comment by CGabo** [comment]
Tried it again. 
Connected to the eWeLink App, working fine, got an IP from dhcp, everything OK.

Deleted it in the app and connected to http://10.10.7.1
Set up with the credentials, but it will not connect to the network. 
As I have 3 new R2 mini's with the same issue, I don't think this is a defect.
Probably some FW issue or some issue with the DHCP.
Older mini's working fine without an issue, prior FW3.6.
